// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymuphoizqtywagwruabz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltdXBob2l6cXR5d2Fnd3J1YWJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzE1MDUsImV4cCI6MjA2NTUwNzUwNX0.8hnY0Uz2fdXxx7Rc4BP7qCumXsDwtmL2EmccejnU8hU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);