// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzqnwmgqxfvjaanmtxwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6cW53bWdxeGZ2amFhbm10eHdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM0MjM3ODQsImV4cCI6MjA0ODk5OTc4NH0.773g-rDA0lpWHatsKEOZzspqIwWxxu_XkMxvFAYu2C4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);